App:
  Name: Plaid Quickstart for WPF

Ui:
  # Use this address to run as standalone client
  WebAddress: https://standalone/index.html
  # Otherwise give the address where we should look for the backend
  # WebAddress: https://localhost:7280/index.html

Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.LifeTime: Information
    # Enable this to get lots of debugging information during Link session
    FrontEnd.Ui: Debug
  Console:
    FormatterName: systemd
    FormatterOptions:
      IncludeScopes: false
      UseUtcTimestamp: true
      TimestampFormat: " [ dd/MM/yyyy HH:mm:ss ] "
