using System.Text.Json.Serialization;

namespace Core.Models;

/// <summary>
/// An error generated by the Plaid service, suitable for transmission over the network (wire)
/// </summary>
/// <remarks>
/// This allows consumption of errors by code which does not consume the Going.Plaid SDK.
/// </remarks>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Matches Plaid API")]
public class WireError
{
    public string error_type { get; set; } = string.Empty;
    public string error_code { get; set; } = string.Empty;
    public string error_message { get; set; } = string.Empty;
    public string? display_message { get; set; }
    public string? error_type_path { get; set; }

    [JsonIgnore]
    public string? Url => (error_type_path is not null) ? $"https://plaid.com/docs/errors/{error_type_path}/#{error_code.ToLowerInvariant()}" : null;
}
